<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Appelez-nous_tb-icon tb-icon-account</name>
   <tag></tag>
   <elementGuidId>da8f1f17-5c36-476f-a525-4501ce005784</elementGuidId>
   <imagePath>Screenshots/Targets/Page_My account - Vervane/i_Appelez-nous_tb-icon tb-icon-account.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_My account - Vervane/i_Appelez-nous_tb-icon tb-icon-account.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.account-button > i.tb-icon.tb-icon-account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div/div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.account-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>79139810-12e9-4009-a60a-b98dc5197a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbc20b82-a0fc-4e5a-8e4b-286fc11bbffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-icon tb-icon-account</value>
      <webElementGuid>e0d73806-587b-4447-91c1-1ae7ae944ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbay-header&quot;)/div[@class=&quot;elementor elementor-51&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-73fc734 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-b54d16e&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-41757a2 w-auto elementor-widget w-auto elementor-widget-tbay-account&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;tbay-element tbay-element-account header-icon&quot;]/div[@class=&quot;tbay-login&quot;]/a[@class=&quot;account-button&quot;]/i[@class=&quot;tb-icon tb-icon-account&quot;]</value>
      <webElementGuid>d157cf01-28b6-4fd5-971e-0fbc5b79e29a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div/div/div/div/a/i</value>
      <webElementGuid>92450ae0-d7da-4a55-970b-eb7676d8dc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a/i</value>
      <webElementGuid>fc0b8c41-dd88-4757-8918-697f9191ace4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
