<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Le prix actuel est .38,000_image-no-effect</name>
   <tag></tag>
   <elementGuidId>94bb05db-8b57-47af-a5cd-5c92d847702b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[4]/div/div[3]/div/div/div/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product.type-product.post-6850.status-publish.last.instock.product_cat-creme-hydratante.product_cat-soin-corps.product_cat-soin-visage.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-simple > div.product-block.grid.product.v1 > div.product-content > div.block-inner > figure.image > a.product-image > img.image-no-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Crème carottes&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a95b52f-263b-4aa8-ae96-41f2ca47ab89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ca9ff73f-9671-4eed-a11b-cf40a401cab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>c3b9bc81-d632-47d2-9d8d-25e46df21cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>869b0e9e-32a9-4a0b-b1e2-2367af92e1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2024/11/1000058067-406x406.webp</value>
      <webElementGuid>84e513b4-ec73-47b4-8b46-7c668d3a7123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-no-effect</value>
      <webElementGuid>3ec87504-1106-41c5-a6b9-ac9f1bf82b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b630e49e-2867-41b8-bbc0-10e3e1fd6531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;display-products products products-grid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;product type-product post-6850 status-publish last instock product_cat-creme-hydratante product_cat-soin-corps product_cat-soin-visage has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;product-block grid product v1&quot;]/div[@class=&quot;product-content&quot;]/div[@class=&quot;block-inner&quot;]/figure[@class=&quot;image&quot;]/a[@class=&quot;product-image&quot;]/img[@class=&quot;image-no-effect&quot;]</value>
      <webElementGuid>e5cdc5b0-f24c-43da-ba35-a1a5e24c204b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/div[3]/div/div/div/figure/a/img</value>
      <webElementGuid>9378495c-d821-48bd-929e-85feaffeff73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://vervane.tn/wp-content/uploads/2024/11/1000058067-406x406.webp')]</value>
      <webElementGuid>7221b55b-50a3-47e1-951a-2a6164f6ce21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/figure/a/img</value>
      <webElementGuid>9be70b79-1ae6-40d4-a73b-7b616b7fd23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vervane.tn/wp-content/uploads/2024/11/1000058067-406x406.webp']</value>
      <webElementGuid>a2fd14cb-2b86-4cb1-8a63-cb86176fd857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
