<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2 crans Solaires Achets  1 Gel Nettoyan_3cecfe</name>
   <tag></tag>
   <elementGuidId>1443a37f-2740-4833-8c81-99b2a9472922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;«2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert» a été ajouté à votre panier&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>815d9fc2-f3b9-42c1-a0f0-8162c5c55c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-message</value>
      <webElementGuid>4f84efa4-2d65-4975-8a9c-ccdfdd7e6bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c7696d05-a5af-455c-8155-2548479b5c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2ee77466-7025-46f4-b4a9-62b905c625ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		«2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert» a été ajouté à votre panier. Voir le panier	</value>
      <webElementGuid>14592f99-bc58-4139-bb01-c7abd33dd794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;woocommerce-notices-wrapper&quot;]/div[@class=&quot;woocommerce-message&quot;]</value>
      <webElementGuid>67aab2c8-e85d-422f-9dae-ba430cb17c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div</value>
      <webElementGuid>ff7a5bda-35c2-45be-bf73-0fcb9436757f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le prix actuel est : د.ت 46,000.'])[1]/following::div[5]</value>
      <webElementGuid>fb3b5623-277a-4ea6-b81a-787ffb624f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='د.ت'])[8]/following::div[5]</value>
      <webElementGuid>486fa154-7206-410f-833c-e052a04ad892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='د.ت'])[9]/preceding::div[5]</value>
      <webElementGuid>ca57cc3c-4b59-4f92-9bc7-b476606afcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='«2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert» a été ajouté à votre panier.']/parent::*</value>
      <webElementGuid>cf4c13be-af39-48f2-a9ff-c378db1733f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div</value>
      <webElementGuid>33603462-7a73-474d-8018-5c77d518a7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
		«2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert» a été ajouté à votre panier. Voir le panier	' or . = '
		«2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert» a été ajouté à votre panier. Voir le panier	')]</value>
      <webElementGuid>073730e5-97ff-4cb3-8bb2-9b894b7707c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
