<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ajouter au panier_wp-post-image</name>
   <tag></tag>
   <elementGuidId>8a4bd903-9b0f-45b5-b46a-e28fb16cab13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-product-gallery__image > a > img.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-7115']/div/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7aa863bc-8e12-4b3a-a694-ecf90aa0c151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>86ccd12e-77c8-4725-83ab-d30ac6049204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>56017446-1690-49cf-b953-e18f58d9f747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>725</value>
      <webElementGuid>f3ae2504-426a-4a1d-a6c6-fdd139c5917f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2025/03/pack-800x725.webp</value>
      <webElementGuid>a21784ca-2a1b-4c63-9fda-e6d0e780e2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-post-image</value>
      <webElementGuid>cf160040-3163-47b9-9415-62cb13db0188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert</value>
      <webElementGuid>05e28511-8745-46ee-a892-2c44e12565e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2025/03/pack.webp</value>
      <webElementGuid>76c92e11-9c37-452a-82ad-ffaaac98cf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2025/03/pack.webp</value>
      <webElementGuid>1aab8009-5de8-4f74-b5e5-32de5849279a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_width</name>
      <type>Main</type>
      <value>1253</value>
      <webElementGuid>c45edc3c-8e26-4cd6-b20e-44e39cbc0dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_height</name>
      <type>Main</type>
      <value>1135</value>
      <webElementGuid>12facf7e-31cd-4c4b-93a8-4bb2aa21819e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e43715b9-30c4-4d78-9323-02e286fec41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-7115&quot;)/div[@class=&quot;single-main-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;image-mains col-lg-6&quot;]/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images no-gallery&quot;]/div[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image&quot;]/a[1]/img[@class=&quot;wp-post-image&quot;]</value>
      <webElementGuid>327fe0dc-00b1-4d79-8489-543249d03fdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-7115']/div/div/div/div/div/div/a/img</value>
      <webElementGuid>82c9cc0f-a327-44b1-8195-28c25ec0c920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert']</value>
      <webElementGuid>91ff5f83-41f8-473c-9151-1fc7b7902836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/a/img</value>
      <webElementGuid>faa8ae92-9f7f-48e4-975b-7ae74cd965eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vervane.tn/wp-content/uploads/2025/03/pack-800x725.webp' and @alt = '2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert']</value>
      <webElementGuid>187a2d66-a685-428e-8065-9450ddf74536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
