<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Appelez-nous_tb-icon tb-icon-heart</name>
   <tag></tag>
   <elementGuidId>b5df4c8e-ce7e-475c-b7df-48f26a376c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.tb-icon.tb-icon-heart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div[2]/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;0&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9631d0fa-7599-4698-b6e5-4027f3eff568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>777679f6-a44e-4429-822c-5ba289ae1e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-icon tb-icon-heart</value>
      <webElementGuid>8125cf51-63a7-4469-b6e1-fa5fac35efae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbay-header&quot;)/div[@class=&quot;elementor elementor-51&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-73fc734 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-b54d16e&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-baae983 w-auto elementor-widget w-auto elementor-widget-tbay-wishlist&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;tbay-element tbay-element-wishlist top-wishlist header-icon&quot;]/a[@class=&quot;wishlist&quot;]/i[@class=&quot;tb-icon tb-icon-heart&quot;]</value>
      <webElementGuid>b2dd04be-ae7b-4783-a6b6-f2a96bd5032f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div[2]/div/div/a/i</value>
      <webElementGuid>0bce3027-3159-45d8-be9e-fe04b09ff44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/i</value>
      <webElementGuid>c1dd8c75-9262-48f4-979d-a87391f98b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
