<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Appelez-nous_tb-icon tb-icon-account</name>
   <tag></tag>
   <elementGuidId>c2a943ac-b775-42a8-81aa-787e795dbfe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > i.tb-icon.tb-icon-account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div/div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.tbay-login > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6e17d1d1-f77a-45ba-9c05-510cd8e171ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc895406-2f5e-4502-ac3a-cd9b87762c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-icon tb-icon-account</value>
      <webElementGuid>0df87a1a-5de7-4d01-a685-6efda4f2066b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbay-header&quot;)/div[@class=&quot;elementor elementor-51&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-73fc734 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-b54d16e&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-41757a2 w-auto elementor-widget w-auto elementor-widget-tbay-account&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;tbay-element tbay-element-account header-icon&quot;]/div[@class=&quot;tbay-login&quot;]/a[1]/i[@class=&quot;tb-icon tb-icon-account&quot;]</value>
      <webElementGuid>d9c6045b-4746-4323-89d3-dcd773c108c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tbay-header']/div/section[2]/div/div[4]/div/div/div/div/div/a/i</value>
      <webElementGuid>ce7946dd-8a22-4d2a-86e9-b277c4c07fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a/i</value>
      <webElementGuid>8b4bfbac-304b-49c4-aaf4-e3cc4a91ad66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
