<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View_image-no-effect</name>
   <tag></tag>
   <elementGuidId>d3cf10bd-4843-436e-b7bc-96afbfebf201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image-no-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[4]/div/div/div/div/div/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77937a08-429f-4924-aba9-f2017856e324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ff948ffc-52d1-4bb3-9893-f3e67dfa2dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>2daf32ef-1e37-46fd-b30d-0508a8f23121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>42e73f78-f8b5-4a6f-b990-0fc0d869ba1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2025/03/pack-406x406.webp</value>
      <webElementGuid>6235871d-1e83-4506-93a5-1b6158df4539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-no-effect</value>
      <webElementGuid>2392c4a4-0e7b-41cd-bf37-19a08ad97338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b12c18f2-b386-4553-8514-368cf68cef12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;display-products products products-grid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;product type-product post-7115 status-publish first instock product_cat-promo product_cat-soin-visage has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;product-block grid product v1&quot;]/div[@class=&quot;product-content&quot;]/div[@class=&quot;block-inner&quot;]/figure[@class=&quot;image&quot;]/a[@class=&quot;product-image&quot;]/img[@class=&quot;image-no-effect&quot;]</value>
      <webElementGuid>a63eb951-411c-4c76-8dc5-a1e9c9c63e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/div/div/div/div/figure/a/img</value>
      <webElementGuid>b63bc7b3-a5b8-481a-9614-1ea29076e442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://vervane.tn/wp-content/uploads/2025/03/pack-406x406.webp')])[2]</value>
      <webElementGuid>22adf819-aa81-4ff3-ac46-ab1551ef18c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/figure/a/img</value>
      <webElementGuid>1ead9b76-6041-433a-8865-8b5a39ab6d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vervane.tn/wp-content/uploads/2025/03/pack-406x406.webp']</value>
      <webElementGuid>5b1f74ca-7f21-4503-bc68-b42e04962992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
