<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View_image-no-effect</name>
   <tag></tag>
   <elementGuidId>498bd6c3-ad6e-4b59-9f16-d5538d54677b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[4]/div/div/div/div/div/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-no-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Huile Horse Tail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8981e77b-0166-4568-aae5-62ecc42195cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4f85c97c-0e06-428a-93a9-4dc4ecfcd9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>31c54e44-7d50-401c-ae1f-0a8d440758cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>a79a7ef4-573a-405a-8bc8-ea43eb46be11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vervane.tn/wp-content/uploads/2024/12/horse-tail-huile-406x406.webp</value>
      <webElementGuid>18f0d424-201a-4154-a7e7-e66c16068b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-no-effect</value>
      <webElementGuid>7a643599-1dd7-4878-a389-1d55cd263c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9f086175-4db6-4e4c-bc9d-93d2ad5d7bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;display-products products products-grid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;product type-product post-6922 status-publish first instock product_cat-huiles product_cat-soin-cheveux has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;product-block grid product v1&quot;]/div[@class=&quot;product-content&quot;]/div[@class=&quot;block-inner&quot;]/figure[@class=&quot;image&quot;]/a[@class=&quot;product-image&quot;]/img[@class=&quot;image-no-effect&quot;]</value>
      <webElementGuid>84ad334d-f753-415e-9332-d6b074dd39b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/div/div/div/div/div/figure/a/img</value>
      <webElementGuid>f7467371-93b0-43f2-afe0-a1aa8dd234c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://vervane.tn/wp-content/uploads/2024/12/horse-tail-huile-406x406.webp')]</value>
      <webElementGuid>a5e997ef-8bf2-4b0a-a98c-0f9123002c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/figure/a/img</value>
      <webElementGuid>54945dd5-b5b4-45a2-823d-677a2a97a8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vervane.tn/wp-content/uploads/2024/12/horse-tail-huile-406x406.webp']</value>
      <webElementGuid>ba3ce7f3-35d4-4888-aa09-9c0a27ec857a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
