<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Top_notify-close</name>
   <tag></tag>
   <elementGuidId>21713234-1f5d-4651-9e2d-e3ece78520d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notify-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notify-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notify-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab52bdfd-2b4e-4954-854f-ca1c65147c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notify-close</value>
      <webElementGuid>10f332b0-b8f8-491c-b866-9549e07c0b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notify-close&quot;)</value>
      <webElementGuid>56a25b2c-8ea9-4bd4-8e34-6287b7e6abb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notify-close']</value>
      <webElementGuid>5c1adea2-6391-4568-ab96-9af92ffef018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='message-purchased']/div[2]</value>
      <webElementGuid>22105c38-cdae-48ef-b0dd-bebb17e5cf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>d3e0537f-168e-4594-84d3-565882142b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notify-close']</value>
      <webElementGuid>99ff003c-175d-4e48-b750-d90627ea82ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
