<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact_tb-icon tb-icon-menu</name>
   <tag></tag>
   <elementGuidId>3a3b726d-fc7d-48cc-9772-ffdc90bb0c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.tb-icon.tb-icon-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper-container']/div[2]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c296bf10-de0a-4783-b715-e86ebcd7b7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb-icon tb-icon-menu</value>
      <webElementGuid>4d2dceb4-ee8d-4380-84db-e7501d0d641a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-container&quot;)/div[@class=&quot;topbar-device-mobile d-xl-none clearfix active&quot;]/div[@class=&quot;active-mobile&quot;]/a[@class=&quot;btn btn-sm mmenu-open&quot;]/i[@class=&quot;tb-icon tb-icon-menu&quot;]</value>
      <webElementGuid>c9a57275-57e6-454e-b84d-7d2c9194b0b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-container']/div[2]/div/a/i</value>
      <webElementGuid>71b865da-467b-44d6-8dd2-7b9d41b33048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>168b43f2-bfba-47eb-9f65-a2fcaa0e6353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
