<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shop</name>
   <tag></tag>
   <elementGuidId>5ed6dc89-8881-4448-9cbe-1cb15f5d6d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-1-XOItJ > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-6579 > a.elementor-item > span.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-1-XOItJ']/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Shop &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb40d236-1b01-42ef-b45a-a4c4c0cd034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>2b6fe594-87b5-4a9c-a879-74030deeb8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>da995876-f529-44b2-8b9f-e677f157fd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-1-XOItJ&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-6579&quot;]/a[@class=&quot;elementor-item&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>d424c6bf-7bb5-4e56-86a7-bf22211a2c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-1-XOItJ']/li[2]/a/span</value>
      <webElementGuid>dff77b21-18b3-4d91-ba62-ef97c5a957c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::span[1]</value>
      <webElementGuid>19ae868f-b560-4ca9-ba02-6a6c90027ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[2]/following::span[2]</value>
      <webElementGuid>60ba32a0-e781-4cc6-8629-059fd8886ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visage'])[2]/preceding::span[1]</value>
      <webElementGuid>c35ff8c9-f4bf-4a4c-95e0-8a60f51ad7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheveux'])[2]/preceding::span[2]</value>
      <webElementGuid>655b7e13-661e-477d-84f2-0aa450da2afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/nav/ul/li[2]/a/span</value>
      <webElementGuid>cea129aa-fba6-4adc-9379-0bc292a4da4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>50cada95-7aeb-45db-ad1e-ef638e176c3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
