<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sr7-bullet_Acheter_sr7-bullet sr7-touchhover</name>
   <tag></tag>
   <elementGuidId>1790048f-db46-4154-9a8a-cbf99f74846b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sr7-module[@id='SR7_1_1']/sr7-content/sr7-bullets/sr7-bullet[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sr7-bullet.sr7-bullet.sr7-touchhover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>sr7-bullet >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sr7-bullet</value>
      <webElementGuid>792f9561-36ec-4472-8f32-87069cab5d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sr7-bullet sr7-touchhover</value>
      <webElementGuid>a62d9ea9-2743-4ad7-91cd-be9800cd8f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4c4b5ea0-d1a8-444f-832a-3eba14bbc198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SR7_1_1&quot;)/sr7-content[1]/sr7-bullets[@class=&quot;sr7-bullets revo-tbay-bullets sr7-ndh sr7-nphc sr7-npvb sr7-touchhover&quot;]/sr7-bullet[@class=&quot;sr7-bullet sr7-touchhover&quot;]</value>
      <webElementGuid>c7ecd000-95d1-4246-81af-275fd83107ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sr7-module[@id='SR7_1_1']/sr7-content/sr7-bullets/sr7-bullet[3]</value>
      <webElementGuid>5f5d109e-3298-4302-a4d2-f0dc8a946d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sr7-bullet[3]</value>
      <webElementGuid>99aa9e5b-134b-4126-8815-bd51cac7ba2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
