<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_76,000_wc-block-components-quantity-s_434f9c</name>
   <tag></tag>
   <elementGuidId>08ed9081-a86e-4be2-a192-217ccfd03ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.wc-block-components-quantity-selector__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Quantité de 2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert dans votre panier.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bab62061-4d16-426a-81e2-a8a7ceb1b750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wc-block-components-quantity-selector__input</value>
      <webElementGuid>cf544901-3050-4b92-8de4-5f22c22de518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>38b7d633-859b-4cf0-b4d3-07f604af5aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04997a9c-ba91-4ae2-b80d-8a5e0ae90261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d30abb43-a2f1-4681-82be-cd9a2d6a47f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>3b7fbcd4-5c89-43a7-bf0c-035f8bb32ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Quantité de 2 Écrans Solaires Achetés = 1 Gel Nettoyant Offert dans votre panier.</value>
      <webElementGuid>058a5efa-9dfa-4bed-b295-43e9ec345d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>159afaf5-34a6-459f-922e-b0ca44285a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;wp-block-woocommerce-cart alignwide&quot;]/div[4]/div[1]/div[@class=&quot;wc-block-components-sidebar-layout wc-block-cart wp-block-woocommerce-filled-cart-block is-large&quot;]/div[@class=&quot;wc-block-components-main wc-block-cart__main wp-block-woocommerce-cart-items-block&quot;]/table[@class=&quot;wc-block-cart-items wp-block-woocommerce-cart-line-items-block&quot;]/tbody[1]/tr[@class=&quot;wc-block-cart-items__row&quot;]/td[@class=&quot;wc-block-cart-item__product&quot;]/div[@class=&quot;wc-block-cart-item__wrap&quot;]/div[@class=&quot;wc-block-cart-item__quantity&quot;]/div[@class=&quot;wc-block-components-quantity-selector&quot;]/input[@class=&quot;wc-block-components-quantity-selector__input&quot;]</value>
      <webElementGuid>e1d82600-f474-46c0-a4e2-2f1f17c9fcaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>220dbf7f-10c7-4776-a574-15e9f91a1e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[4]/div/div/div[2]/table/tbody/tr/td[2]/div/div[3]/div/input</value>
      <webElementGuid>0e976209-65ff-4263-83e5-487d3ab5ad9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>40ddceac-681e-49a3-83f9-2d061a905f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>bce1f8a4-7726-4fca-abcf-16f7a492ac41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
